services:
  noums-ebank-discovery-service2:
   build: ./discovery-service2
   container_name: noums-ebank-discovery-service2
   ports:
    - '8761:8761'
   expose:
    - '8761' 
   healthcheck:
    test: [ "CMD","curl","-f","http://localhost:8761/actuator/health" ]
    interval: 10s
  noums-ebank-config-service2:
   build: ./config-service2
   container_name: noums-ebank-config-service2
   ports:
    - '9999:9999' 
   expose:
    - '9999'
   environment:
    - DISCOVERY_SERVICE_URL=http://noums-ebank-discovery-service2:8761/eureka
   healthcheck:
    test: [ "CMD","curl","-f","http://localhost:9999/actuator/health" ]
    interval: 10s
    retries: 4
   depends_on:
    noums-ebank-discovery-service2:
     condition: service_healthy
  noums-ebank-customer-service2:
   build: ./customer-service2
   container_name: noums-ebank-customer-service2
   ports:
    - '8081:8081'
   expose:
    - '8081'
   environment:
    - DISCOVERY_SERVICE_URL=http://noums-ebank-discovery-service2:8761/eureka
    - CONFIG_SERVICE_URL=http://noums-ebank-config-service2:9999
   healthcheck:
    test: [ "CMD","curl","-f","http://localhost:8081/actuator/health" ]
    interval: 10s
    retries: 4
   depends_on:
    noums-ebank-config-service2:
     condition: service_healthy
  noums-ebank-account-service2:
   build: ./account-service2
   container_name: noums-ebank-account-service2
   ports:
    - '8082:8082'
   expose:
    - '8082'
   environment:
    - DISCOVERY_SERVICE_URL=http://noums-ebank-discovery-service2:8761/eureka
    - CONFIG_SERVICE_URL=http://noums-ebank-config-service2:9999
   depends_on:
    noums-ebank-customer-service2:
     condition: service_healthy
  noums-ebank-gateway-service2:
   build: ./gateway-service2
   container_name: noums-ebank-gateway-service2
   ports:
    - '8888:8888'
   expose:
    - '8888'
   environment:
    - DISCOVERY_SERVICE_URL=http://noums-ebank-discovery-service2:8761/eureka
    - CONFIG_SERVICE_URL=http://noums-ebank-config-service2:9999
   depends_on:
    noums-ebank-config-service2:
     condition: service_healthy
